"""This module contains the implementation of the symbolic regression methods"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/lib_nbs/sr/01_core.ipynb.

# %% auto #0
__all__ = ['EPS', 'pearson_between_vectors_vmap', 'spearman_rho_vmap', 'FFNN_theta_to_mu', 'TwoBodyModel', 'class_loss',
           'loss_SR1', 'derivative_loss_alpha_multi', 'loss_SR2', 'derivative_loss_alpha_multi_vk', 'loss_SR3',
           'curved_edge', 'empirical_corr_matrix', 'flatten_upper', 'pearson_between_vectors', 'cosine_sim',
           'spearman_rho', 'compare_theta_corr', 'auc_from_scores_labels']

# %% ../../nbs/lib_nbs/sr/01_core.ipynb #85744adf
import jax
from jax import numpy as jnp
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as patches
import numpy as np
from typing import Any, Callable, Optional, Tuple, Dict, Sequence
from flax import linen as nn

# %% ../../nbs/lib_nbs/sr/01_core.ipynb #ce005578
class FFNN_theta_to_mu(nn.Module):
    """simple feed forward net from theta to mu1"""
    hidden_dim: int
    num_layers: int

    @nn.compact
    def __call__(self, theta):
        x = theta
        for _ in range(self.num_layers):
            x = nn.Dense(self.hidden_dim)(x)#, kernel_init=nn.initializers.he_normal())(x)
            x = nn.tanh(x)

        x = nn.Dense(1)(x)
        return x


class TwoBodyModel:
    def __init__(self, pairs, key, add_constant: bool=False):
        self.pairs = pairs
        N_params = len(pairs) + 1*add_constant
        self.add_constant = add_constant
        self.alpha = jax.random.normal(key,(N_params,)) * 0.1
        self.pair_indices = jnp.array([[int(a[1:]), int(b[1:]) ]  for (a, b) in self.pairs])

    def evaluate_with_gradients(self, X, options=None):
        Xj = jnp.asarray(X)  # (N, D)
        a_idx = self.pair_indices[:, 0]
        b_idx = self.pair_indices[:, 1]
        alpha = self.alpha  # (K,)


        contrib_to_a = Xj[:, b_idx] * alpha  # (N, K)
        contrib_to_b = Xj[:, a_idx] * alpha  # (N, K)

        # update a container
        dy = jnp.zeros_like(Xj)
        dy = dy.at[:, a_idx].add(contrib_to_a)
        dy = dy.at[:, b_idx].add(contrib_to_b)

        return dy


    def predict(self, X):
        Y = 0
        for k, (a, b) in enumerate(self.pairs):
            Y += self.alpha[k] * X[:, int(a[1:])] * X[:, int(b[1:])]
        if self.add_constant:
            Y += self.alpha[-1]
        return Y


def class_loss(tree, X, options, Y):
    """classification loss used for the 2BC witb SR1"""
    pred = tree.predict(X)
    #"loss(x,y) = -y*log(1/(1+exp(-x)))-(1-y)*log(1-1/(1+exp(-x)))",  # Define sigmoid within loss function

    sig = 1/(1+jnp.exp(-pred))
    Y = Y[:,0]
    loss = -jnp.mean(Y * jnp.log(sig) + (1-Y) * jnp.log(1-sig))

    return loss


def loss_SR1(alpha, model, X, Y, options):
    """loss used for the 2BC witb SR1"""
    model.alpha = alpha
    return class_loss(model, X, options, Y)



def derivative_loss_alpha_multi(tree, X, options, G):
    """loss aligning the gradiant"""
    dy = tree.evaluate_with_gradients(X, options)#.swapaxes(0,1)
    dy = dy / (jnp.linalg.norm(dy, axis=1, keepdims=True) + 1e-12)

    MSE = jnp.mean(jnp.sum((dy - G) ** 2, axis=0))

    return MSE


def loss_SR2(alpha, model, dataset, G, options):
    """loss used for the 2BC witb SR2"""
    model.alpha = alpha
    return derivative_loss_alpha_multi(model, dataset, options, G)



EPS = 1e-12

def derivative_loss_alpha_multi_vk(tree, X, options, vk, G):
    """
        loss projecting and aligning the gradiant
        Args:
            dy: (S, N)  gradients of tree w.r.t inputs
            vk: (S, N, m) projector vectors per sample (m projectors)
            G: (S, m) target projected gradients per sample
        Returns MSE between normalized projected dy and normalized G (averaged over m).
    """

    # Evaluate gradients of f
    dy = tree.evaluate_with_gradients(X, options)   # -> (S, N)
    dy = jnp.asarray(dy)
    assert dy.ndim == 2, f"dy should be (S, N); got {dy.shape}"

    # Norm. dy per-sample across features (axis=1)
    dy = dy / (jnp.linalg.norm(dy, axis=1, keepdims=True) + EPS)  # (S, N)

    # Prepare vk, should be (S, N, m)
    vk = jnp.asarray(vk)
    assert vk.ndim == 3, f"vk should be (S, N, m); got {vk.shape}"
    # Normalize vk per-sample across features (axis=1), keepdims so broadcasting works
    vk = vk / (jnp.linalg.norm(vk, axis=1, keepdims=True) + EPS)  # (S, N, m)

    # Project dy onto each Vk, result shape (S, m)
    proj = jnp.einsum('sn,snm->sm', dy, vk)  # (S, m)

    # Global normalization across samples for each projector
    proj = proj / (jnp.linalg.norm(proj, axis=0, keepdims=True) + EPS)  # (S, m)
    G = jnp.asarray(G)
    assert G.shape == proj.shape, f"G shape {G.shape} must match proj shape {proj.shape}"
    G = G / (jnp.linalg.norm(G, axis=0, keepdims=True) + EPS)  # (S, m)

    #MSE (given the normalization, its = to cosine sim.)
    mse = jnp.mean((proj - G) ** 2)

    return mse



def loss_SR3(alpha, model, dataset, vk, G, options):
    """loss used for 2BC with SR3"""
    model.alpha = alpha
    return derivative_loss_alpha_multi_vk(model, dataset, options, vk, G)



def curved_edge(ax, x1, y1, x2, y2, curvature=0.2, **plot_kwargs):
    """
        Draw a curved (quadratic Bézier) edge between (x1,y1) and (x2,y2).
        curvature > 0 bends left, curvature < 0 bends right.
    """
    xm, ym = (x1+x2)/2, (y1+y2)/2   # midpoint
    dx, dy = (y2-y1), -(x2-x1)      # perpendicular direction
    nx, ny = dx*np.sign(curvature), dy*np.sign(curvature)
    nx, ny = nx*curvature, ny*curvature

    control = (xm + nx, ym + ny)

    path = Path([(x1,y1), control, (x2,y2)],
                [Path.MOVETO, Path.CURVE3, Path.CURVE3])
    patch = patches.PathPatch(path, fill=False, **plot_kwargs)
    ax.add_patch(patch)





### metrics used for comparaison ###



def empirical_corr_matrix(X, centered=True):
    # X: (N, L) spins (values e.g. ±1)
    N = X.shape[0]
    if centered:
        Xc = X - jnp.mean(X, axis=0, keepdims=True)
    else:
        Xc = X
    C = (Xc.T @ Xc) / (N - 1)
    return C  # shape (L, L)

# helper: flatten only unique pairs (i<=j) or use full flatten
def flatten_upper(mat):
    L = mat.shape[0]
    iu = jnp.triu_indices(L)
    return mat[iu]  # length L*(L+1)/2

def pearson_between_vectors(a, b, eps=1e-12):
    a = a - jnp.mean(a)
    b = b - jnp.mean(b)
    num = jnp.sum(a*b)
    den = jnp.sqrt(jnp.sum(a*a) * jnp.sum(b*b)) + eps
    return num/den

pearson_between_vectors_vmap = jax.vmap(pearson_between_vectors, in_axes=(0, None))


def cosine_sim(a, b, eps=1e-12):
    return (jnp.dot(a, b)) / (jnp.linalg.norm(a) * jnp.linalg.norm(b) + eps)



def spearman_rho(a, b):
    # ranks via argsort twice -> rank starting at 0
    def ranks(x):
        return jnp.argsort(jnp.argsort(x).astype(jnp.int32)).astype(jnp.float32)
    ra, rb = ranks(a), ranks(b)
    return pearson_between_vectors(ra, rb)



spearman_rho_vmap = jax.vmap(spearman_rho, in_axes=(0, None))


# convenience: compare theta (L,L) to empirical C
def compare_theta_corr(theta, X, C, method="pearson", use_upper=True):
    #C = empirical_corr_matrix(X, centered=True)
    # symmetrize theta if desired
    theta_sym = 0.5*(theta + theta.T)
    if use_upper:
        a = flatten_upper(theta_sym)
        b = flatten_upper(C)
    else:
        a = theta_sym.ravel()
        b = C.ravel()
    if method == "pearson":
        return pearson_between_vectors(a, b)
    if method == "cosine":
        return cosine_sim(a, b)
    if method == "spearman":
        return spearman_rho(a, b)
    raise ValueError("unknown method")


def auc_from_scores_labels(scores, labels):
    # labels in {0,1}
    # rank scores: tie-breaking by argsort; ranks start at 1
    ranks = jnp.argsort(jnp.argsort(scores)) + 1.0
    pos = labels == 1
    n_pos = jnp.sum(pos)
    n_neg = labels.shape[0] - n_pos
    # sum ranks of positive
    sum_ranks_pos = jnp.sum(ranks * pos)
    auc = (sum_ranks_pos - n_pos*(n_pos+1)/2.0) / (n_pos * n_neg + 1e-12)
    return auc


