project:
  type: website
  output-dir: _docs
  preview:
    port: 4200

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  title: "QDisc"
  site-url: "https://qic-ibk.github.io/qdisc/"
  description: ""
  repo-branch: main
  repo-url: "https://github.com/qic-ibk/qdisc"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:      
    logo: figs/qdisc_logo.png
    background: "#f0f0f0ff"
    search: true      
    right:
      - icon: github
        href: "https://github.com/qic-ibk/qdisc" 
  sidebar:
    style: floating

metadata-files: [sidebar.yml]