project:
  type: website
  output-dir: _docs
  preview:
    port: 4200

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  title: "QDisc"
  site-url: "https://qic-ibk.github.io/qdisc/"
  description: ""
  repo-branch: main
  repo-url: "https://github.com/qic-ibk/qdisc"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:      
    logo: figs/qdisc_logo.png
    background: "#1a2235"
    foreground: "#ffffff"
    search: true      
    right:
      - icon: github
        href: "https://github.com/qic-ibk/qdisc" 
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - text: Get started
        href: index.ipynb
      - section: Examples
        contents:
          - examples/index_examples.ipynb
          - examples/qdisc_Rydberg.ipynb
          - examples/qdisc_ClusterIsing.ipynb
          - examples/qdisc_FKM.ipynb
      - section: Documentation
        contents:
          - lib_nbs/index_docs.ipynb
          - lib_nbs/clustering/01_core.ipynb
          - lib_nbs/dataset/01_core.ipynb
          - lib_nbs/nn/01_core.ipynb
          - lib_nbs/sr/01_core.ipynb
          - lib_nbs/vae/01_core.ipynb
      - section: Tutorials
        contents:
          - tutorials/J1J2_tuto1_VAE.ipynb
          - tutorials/J1J2_tuto2_SR.ipynb

