# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qdisc',
                'doc_host': 'https://PaulinDS.github.io',
                'git_url': 'https://github.com/PaulinDS/qdisc',
                'lib_path': 'qdisc'},
  'syms': {'qdisc.core': {'qdisc.core.foo': ('core.html#foo', 'qdisc/core.py')}}}
